---
title: "holdenl_OriginalHomeworkCode_01"
author: Lillian Holden
output: html_document
date: "2023-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,}
install.packages(stringr)
library(stringr)
```

#Challenge #1
```{r,}
v1 <- c("Stately,", "plump", "Buck", "Mulligan", "came", "from", "the", "stairhead,", "bearing", "a", "bowl", "of", "lather", "on", "which", "a", "mirror", "and", "a", "razor", "lay", "crossed.") 
v1
str_split(v1,"Buck", n=1, simplify=FALSE)
v1[c(3,6,9,12,15,18,21)]
```
#Challenge #2
```{r,}
m<- matrix(data=1:80, nrow=8, ncol=10, byrow=TRUE)
m
x<-m[,2]
x<-m[c(2,3,6)]
x
x<-m[c(6,8),]
x
x<-m[c(2:6),c(2:9)]
x
```
#Challenge #3
```{r,}
a<-array(data=400:1, dim=c(5,5,4,4))
a
a[1,1,1,2]
a[2,3,2,]
a[1:5,1:5,3,3]
```
#Challenge #4
```{r,}
Lemuroidea<-c("Cheirogaleidae", "Lepilemuridae","Indridae", "Lemuridae", "Daubentoniidae")
Lorisoidea<-c("Lorisidae","Galagidae")
Strepsirhini<-list("Lemuroidea","Lorisoidea")
Strepsirhini
Lemuroidea<-c("Cheirogaleidae", "Lepilemuridae","Indridae", "Lemuridae", "Daubentoniidae")
Lorisoidea<-c("Lorisidae","Galagidae")
Strepsirhini<-list("Lemuroidea","Lorisoidea")
names(Strepsirhini)<-list("Lemuroidea","Lorisoidea")
Strepsirhini
Lemuroidea<-c("Cheirogaleidae", "Lepilemuridae","Indridae", "Lemuridae", "Daubentoniidae")
Lorisoidea<-c("Lorisidae","Galagidae")
Strepsirhini<-list(Lemuroidea,Lorisoidea)
names(Strepsirhini)<-list("Lemuroidea","Lorisoidea")
Strepsirhini
Tarsioidea<-c("Tarsiidae")
Catarrhini<-c("Cercopithecidae","Hylobatidae","Hominidae")
Platyrrhini<-c("Cebidae","Atelidae","Pitheciidae")
Anthropoidea<-c("Platyrrhini","Catarrhini")
Haplorhini<-list(Anthropoidea,Tarsioidea)
names(Haplorhini)<-list("Anthropoidea","Tarsioidea")
Haplorhini
Haplorhini<-list(Anthropoidea,Platyrrhini,Catarrhini,Tarsioidea)
names(Haplorhini)<-list("Anthropoidea","Platyrrhini","Catarrhini","Tarsioidea")
Haplorhini
Primates<-list(Haplorhini,Strepsirhini)
names(Primates)<-list("Haplorhini","Strepsirhini")
Primates
```
#Challenge #5 
```{r,}
m3<-matrix(data=c(3,0,1,23,1,2,33,1,1,42,0,1,41,0,2),nrow=5,ncol=3,byrow=TRUE)
data.frame(m3)
df <- data.frame(m3)
df[,2] <- as.logical(df[,2])
df[,3] <- as.factor(df[,3])
str(df)
```
